# Generated by Django 4.0.3 on 2022-03-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='avatar',
            field=models.TextField(default='default_avatar.png', max_length=100),
        ),
    ]
