# Generated by Django 4.0.3 on 2022-03-22 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^(09)[0-9]{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
