# Generated by Django 4.0.3 on 2022-03-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_avatar_historicalaccount_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
