# Generated by Django 4.0.3 on 2022-03-22 00:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_created_remove_account_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='زمان ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2022, 3, 22, 0, 34, 6, 659265, tzinfo=utc), editable=False, verbose_name='آخرین زمان تغییر'),
            preserve_default=False,
        ),
    ]
