# Generated by Django 4.0.3 on 2022-04-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='optional_information',
            field=models.CharField(blank=True, max_length=200, verbose_name='توضیحات اضافه'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='optional_information',
            field=models.CharField(blank=True, max_length=200, verbose_name='توضیحات اضافه'),
        ),
    ]
