# Generated by Django 4.0.3 on 2022-03-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_username_historicalaccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='username',
        ),
    ]
