# Generated by Django 4.0.3 on 2022-03-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_account_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
