# Generated by Django 4.0.3 on 2022-03-27 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietTemplatePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=100, verbose_name='محتوا')),
                ('meal', models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام')], max_length=100, verbose_name='وعده غذایی')),
                ('week_day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه')], max_length=100, verbose_name='روز هفته')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده قطعه رژیم')),
            ],
            options={
                'verbose_name': 'بخش تمپلیت رژیم',
                'verbose_name_plural': 'بخش\u200cهای تمپلیت رژیم',
            },
        ),
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='شروع')),
                ('end_date', models.DateTimeField(verbose_name='پایان')),
                ('type', models.CharField(choices=[('diabetes_control', 'کنترل دیابت'), ('specialized_program', 'برنامه مخصوص غذایی')], max_length=100, verbose_name='نوع ویزیت')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_visits', to=settings.AUTH_USER_MODEL, verbose_name='پزشک')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'ویزیت',
                'verbose_name_plural': 'ویزیت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تمپلیت')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده تمپلیت رژیم')),
                ('template_parts', models.ManyToManyField(to='diabetes_control.diettemplatepart', verbose_name='بخش\u200cهای تمپلیت')),
            ],
            options={
                'verbose_name': 'تمپلیت رژیم',
                'verbose_name_plural': 'تمپلیت\u200cهای رژیم',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000, verbose_name='محتوا')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diabetes_control.visittime', verbose_name='ویزیت')),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetes_control.template', verbose_name='تمپلیت رژیم')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diabetes_control.visittime')),
            ],
            options={
                'verbose_name': 'رژیم غذایی',
                'verbose_name_plural': 'رژیم\u200cهای غذایی',
            },
        ),
    ]
