# Generated by Django 4.0.3 on 2022-03-22 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DietTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=100, verbose_name='محتوا')),
                ('meal', models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام')], max_length=100, verbose_name='وعده غذایی')),
            ],
        ),
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='شروع')),
                ('end_date', models.DateTimeField(verbose_name='پایان')),
                ('type', models.CharField(choices=[('diabetes_control', 'کنترل دیابت'), ('specialized_program', 'برنامه مخصوص غذایی')], max_length=100, verbose_name='نوع ویزیت')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_visits', to=settings.AUTH_USER_MODEL, verbose_name='پزشک')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000, verbose_name='محتوا')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diabetes_control.visittime', verbose_name='ویزیت')),
            ],
        ),
        migrations.CreateModel(
            name='DietPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه')], max_length=100, verbose_name='روز هفته')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_parts', to='diabetes_control.diet', verbose_name='رژیم')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_template', to='diabetes_control.diettemplate', verbose_name='تمپلیت رژیم')),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diabetes_control.visittime'),
        ),
    ]
