# Generated by Django 4.0.3 on 2022-04-07 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='template',
        ),
        migrations.RemoveField(
            model_name='diettemplatepart',
            name='owner',
        ),
        migrations.AddField(
            model_name='diet',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام رژیم'),
        ),
        migrations.AddField(
            model_name='diettemplatepart',
            name='diet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diabetes_control.diet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
