# Generated by Django 4.0.3 on 2022-04-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_control', '0002_remove_diet_template_remove_diettemplatepart_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittime',
            name='type',
            field=models.CharField(choices=[('diabetes_control', 'کنترل دیابت'), ('specialized_program', 'برنامه مخصوص غذایی')], default='diabetes_control', max_length=100, verbose_name='نوع ویزیت'),
        ),
    ]
