# Generated by Django 4.0.3 on 2022-04-08 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diabetes_control', '0003_alter_visittime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='هدف رژیم')),
            ],
        ),
        migrations.RenameModel(
            old_name='Diet',
            new_name='SpecializedDiet',
        ),
        migrations.RemoveField(
            model_name='diettemplatepart',
            name='diet',
        ),
        migrations.AddField(
            model_name='diettemplatepart',
            name='specialized_diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes_control.specializeddiet'),
        ),
        migrations.CreateModel(
            name='FreeDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام رژیم')),
                ('accounts', models.ManyToManyField(related_name='diet_accounts', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetes_control.dietkind')),
            ],
        ),
        migrations.AddField(
            model_name='diettemplatepart',
            name='free_diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes_control.freediet'),
        ),
    ]
