# Generated by Django 4.0.3 on 2022-04-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_diet', '0001_initial'),
        ('diabetes_control', '0005_remove_freediet_kind_freediet_free_diet_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diettemplatepart',
            name='free_diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='free_diet.freediet'),
        ),
        migrations.DeleteModel(
            name='FreeDiet',
        ),
    ]
