# Generated by Django 4.0.3 on 2022-04-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_control', '0006_alter_diettemplatepart_free_diet_delete_freediet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diettemplatepart',
            name='free_diet',
        ),
    ]
