# Generated by Django 4.0.3 on 2022-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='default_avatar.png', upload_to=''),
        ),
    ]
