# Generated by Django 4.0.3 on 2022-04-08 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام رژیم')),
                ('free_diet_kind', models.CharField(choices=[('weightgain', 'افزایش وزن'), ('weightloss', 'کاهش وزن')], default='weightloss', max_length=100, verbose_name='نوع رژیم')),
                ('accounts', models.ManyToManyField(related_name='diet_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
