# Generated by Django 4.0.3 on 2022-04-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_diet', '0002_freediet_diet_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDietTemplatePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=100, verbose_name='محتوا')),
                ('meal', models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام')], max_length=100, verbose_name='وعده غذایی')),
                ('week_day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه')], max_length=100, verbose_name='روز هفته')),
                ('free_diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='free_diet.freediet')),
            ],
        ),
    ]
