# Generated by Django 4.0.3 on 2022-04-16 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('free_diet', '0003_freediettemplatepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDietInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_diets',
                                              to=settings.AUTH_USER_MODEL)),
                ('free_diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances',
                                                to='free_diet.freediet')),
            ],
        ),
    ]
