# Generated by Django 4.0.3 on 2022-04-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_diet', '0004_freedietinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freediet',
            options={'verbose_name': 'رژیم رایگان غذایی', 'verbose_name_plural': 'رژیم\u200cهای رایگان غذایی'},
        ),
        migrations.AlterModelOptions(
            name='freedietinstance',
            options={'verbose_name': 'نمونه رژیم رایگان غذایی', 'verbose_name_plural': 'نمونه\u200cهای رژیم رایگان غذایی'},
        ),
        migrations.AlterModelOptions(
            name='freediettemplatepart',
            options={'verbose_name': 'تمپلیت رژیم رایگان غذایی', 'verbose_name_plural': 'تمپلیت\u200cهای رژیم رایگان غذایی'},
        ),
    ]
