# Generated by Django 4.0.3 on 2022-04-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_diet', '0005_alter_freediet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freediet',
            name='accounts',
        ),
    ]
