# Generated by Django 4.0.3 on 2022-04-16 23:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('free_diet', '0006_remove_freediet_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedietinstance',
            name='started_at',
            field=models.DateField(auto_now_add=True, db_index=True, default=datetime.datetime(2022, 4, 16, 23, 16, 4, 132326, tzinfo=utc), verbose_name='زمان ساخت'),
            preserve_default=False,
        ),
    ]
